### PR TITLE
ztp: add standard cluster deployment

### PR DESCRIPTION
**Pull request by serngawy**
Signed-off-by: melserngawy <melserng@redhat.com>

### CODE REVIEW

**Comment by lack** [comment]
What roles will nodes have in the standard cluster deploy?  For example, the extra-manifests labels need to be changed if we're deploying any nodes not in the "master" machine config pool.

**Review by yrobla — APPROVED** [review]

**Comment by serngawy** [comment]
> What roles will nodes have in the standard cluster deploy? For example, the extra-manifests labels need to be changed if we're deploying any nodes not in the "master" machine config pool.

The Node Role has been added in anther PR https://github.com/openshift-kni/cnf-features-deploy/pull/685 I will re-base if it get merged first

**Review by yrobla — APPROVED** [review]

**Pull request merged**
