### PR TITLE
Add an option to run latency test together with other tests

### PR DESCRIPTION
**Pull request by cynepco3hahue**
During call to `hack/run-functests.sh` check the `LATENCY_TEST_RUN`
environment variable and when it equals to true, run latency tests
together with other tests.

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@sabinaaledort @fedepaol FYI

**Comment by fedepaol** [comment]
Sorry for the late review. 
Aren't the latency tests run by default with the performance suite?

**Comment by cynepco3hahue** [comment]
> Sorry for the late review.
> Aren't the latency tests run by default with the performance suite?

Nope, you should pass additional ENV variables to the container.

**Comment by fedepaol** [comment]
my bad, I thought they were only for setting the parameters.

**Comment by cynepco3hahue** [comment]
> my bad, I thought they were only for setting the parameters.

No worries :)

**Pull request merged**
