### PR TITLE
cnf-tests: update submodules

### PR DESCRIPTION
**Pull request by rbaturov**
Update submodules of cnf-tests to point to the latest commits, by running `git submodule update --remote`.

### CODE REVIEW

**Comment by liornoy** [comment]
This is for updating the cnf-tests container image

**Comment by liornoy** [comment]
@SchSeba can you add the approve label please?

**Comment by rbaturov** [comment]
> @rbaturov may you re-update the submodules to consume latest updates on NTO at least? see [#1889 (comment)](https://github.com/openshift-kni/cnf-features-deploy/pull/1889#issuecomment-2104241818)

Done!

**Comment by lack** [comment]
I'm happy to override the potentially flaky test if you can let me know that it's not related to the changes.

**Comment by liornoy** [comment]
I don't think those metallb failures should happen. needs further investigation.

**Comment by shajmakh** [comment]
@liornoy can you please verify if the metallb failures are legit and if there is card to track them? the updates in this PR is needed for other PRs

**Comment by zeeke** [comment]
> @liornoy can you please verify if the metallb failures are legit and if there is card to track them? the updates in this PR is needed for other PRs

There is no metallb failure in jobs
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-kni_cnf-features-deploy/1881/pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests/1806354065479700480

```
Ginkgo ran 1 suite in 4m9.215344699s
Test Suite Passed
[WARN] Tests failed:
Tier 2 tests for nto
Tier 2 tests for nto-performance
```

The output is not very clear, but rebasing this PR on top of
- https://github.com/openshift-kni/cnf-features-deploy/pull/1935

should fix it, a the problem is the go version

```
go: errors parsing go.mod:
/go/src/github.com/openshift-kni/cnf-features-deploy/cnf-tests/submodules/cluster-node-tuning-operator/go.mod:3: invalid go version '1.22.0': must match format 1.23
/go/src/github.com/openshift-kni/cnf-features-deploy/cnf-tests/submodules/cluster-node-tuning-operator/go.mod:5: unknown directive: toolchain
```

**Comment by rbaturov** [comment]
@SchSeba @liornoy Can we have the needed labels please?

**Pull request merged**
