### PR TITLE
Ptp slavery

### PR DESCRIPTION
**Pull request by yuvalk**
eradicate slavery from ptp

### CODE REVIEW

**Comment by vitus133** [comment]
@yuvalk 
I think it's now called "subordinate" and not "client"
The "mastery" still remains

**Comment by yuvalk** [comment]
> @yuvalk
> I think it's now called "subordinate" and not "client"
> The "mastery" still remains

https://sourceforge.net/p/linuxptp/mailman/message/37183551/

**Comment by yuvalk** [comment]
assuming we want to wait with this till patches are accepted in linuxptp
and actually until they are accepted into 
I'll close and reopen if/when appropriate

**Pull request closed without merging**
