### PR TITLE
Provide NUMA node for hugepages allocation

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by slintes** [comment]
/lgtm

but let's wait for e2e
/hold

**Comment by slintes** [comment]
e2e-gcp successful

/hold cancel

**Comment by cynepco3hahue** [comment]
`e2e-gcp` passed

**Comment by cynepco3hahue** [comment]
@MarSik Can you please give `/approve`

**Comment by MarSik** [comment]
But tests are still failing. Is that caused by something else?

**Comment by cynepco3hahue** [comment]
> But tests are still failing. Is that caused by something else?

The one that interesting us, is `e2e-gcp` other lanes fails on unrelated stuff.

**Pull request merged**
