### PR TITLE
rename Bare Metal Event Relay feature

### PR DESCRIPTION
**Pull request by jzding**
The baremetal-hardware-event-proxy-operator is renamed to bare-metal-event-relay. This PR implements this change in ztp.
Amq Interconnect is required for Bare Metal Event Relay to work, therefore add amq deployment in the examples.

Signed-off-by: Jack Ding <jacding@redhat.com>

### CODE REVIEW

**Review by josephdrichard — APPROVED** [review]
/lgtm

**Review by Missxiaoguo — APPROVED** [review]

**Pull request merged**
