### PR TITLE
improve du performance profile

### PR DESCRIPTION
**Pull request by yuvalk**
- add general performance profile to 5g reference
- add pci=realloc to ran-overlays

pci=realloc is needed on some BMs where BIOS fail to properly set BARs

### CODE REVIEW

**Comment by yuvalk** [comment]
@MarSik @SchSeba @vitus133 
WDYT?

**Comment by vitus133** [comment]
Great, and thanks for suffix optimization

**Comment by yuvalk** [comment]
@vitus133 I've modified this PR to be just about the du performance profile
as seems the pci=realloc is not needed (yay)
please review

**Comment by vitus133** [comment]
And again, thanks for the optimization :)

**Comment by SchSeba** [comment]
Thanks @yuvalk I will leave the review to @vitus133

**Pull request merged**
