### PR TITLE
cnf-tests: sriov-network-operator bump

### PR DESCRIPTION
**Pull request by zeeke**
SR-IOV Network Operator dependency bumped with commands:

```
go mod edit -replace\
github.com/k8snetworkplumbingwg/sriov-network-operator=\
github.com/openshift/sriov-network-operator@release-4.12
go mod tidy
go mod vendor
```

This update is needed to fix the following test:

```
[Fail] 
  [sriov] operator Generic SriovNetworkNodePolicy Virtual Functions 
    [It] should release the VFs once the pod deleted and same VFs can be used by the new created pods
```

- https://github.com/openshift/sriov-network-operator/pull/681 
  -  https://github.com/openshift/sriov-network-operator/pull/681/commits/8cdbc1ccfd28ebecf67e0b3b38f26ae3f9de8fc3

### CODE REVIEW

**Comment by zeeke** [comment]
Alos bumped `k8s.io/*` to v0.24.1 to solve dependency conflicts with sriov-network-operator.

**Comment by SchSeba** [comment]
Thanks!

/lgtm
/approve

**Comment by SchSeba** [comment]
close the wrong PR sorry

**Comment by SchSeba** [comment]
/hold 
until we have a clean sriov 4.12 build base on golang 1.18

**Comment by zeeke** [comment]
/hold wait for
- https://github.com/openshift/sriov-network-operator/pull/686

**Comment by SchSeba** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
