### PR TITLE
Fix setup-test-cluster node selector

### LINKED ISSUE #146: oc get nodes with selector should be separated by commas
https://github.com/openshift-kni/cnf-features-deploy/blob/ef3c35cdbfdcad970040278bfec121233edb3993/hack/setup-test-cluster.sh#L11-L12

```
-l, --selector='': Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2)
```

Otherwise, it uses just the latest selector:

```
[kni@kni1-bootstrap cnv]$ oc get nodes
NAME                                         STATUS   ROLES               AGE   VERSION
kni1-master-0.cloud.lab.eng.bos.redhat.com   Ready    worker,worker-cnf   26h   v1.17.1
kni1-master-1.cloud.lab.eng.bos.redhat.com   Ready    worker,worker-cnf   26h   v1.17.1
kni1-vmaster-0                               Ready    master              27h   v1.17.1
kni1-vmaster-1                               Ready    master              27h   v1.17.1
kni1-vmaster-2                               Ready    master              27h   v1.17.1
kni1-worker-0.cloud.lab.eng.bos.redhat.com   Ready    worker              27h   v1.17.1
```

```
$ oc get nodes --selector='node-role.kubernetes.io/worker' --selector='!node-role.kubernetes.io/worker-cnf'
NAME                                         STATUS   ROLES    AGE   VERSION
kni1-vmaster-0                               Ready    master   27h   v1.17.1
kni1-vmaster-1                               Ready    master   27h   v1.17.1
kni1-vmaster-2                               Ready    master   27h   v1.17.1
kni1-worker-0.cloud.lab.eng.bos.redhat.com   Ready    worker   27h   v1.17.1
```
vs
```
$ oc get nodes --selector='node-role.kubernetes.io/worker,!node-role.kubernetes.io/worker-cnf'
NAME                                         STATUS   ROLES    AGE   VERSION
kni1-worker-0.cloud.lab.eng.bos.redhat.com   Ready    worker   27h   v1.17.1
```

### PR DESCRIPTION
**Pull request by e-minguez**
Fixes #146

### CODE REVIEW

**Comment by yuvalk** [comment]
good catch!

**Comment by yuvalk** [comment]
> good catch!

hmm, actually, isn't the !master enough?

**Comment by e-minguez** [comment]
> > good catch!
> 
> hmm, actually, isn't the !master enough?

I guess this is to prevent CNF features running on 'infra' nodes https://docs.openshift.com/container-platform/4.3/machine_management/creating-infrastructure-machinesets.html (`node-role.kubernetes.io/infra`)

**Comment by SchSeba** [comment]
Hi @e-minguez you close this one?

can I reopen it?

**Comment by e-minguez** [comment]
> Hi @e-minguez you close this one?
> 
> can I reopen it?

Sure. I was cleaning old unmerged PRs, but if you think this would be helpful...

**Pull request closed without merging**
