### PR TITLE
OCPBUGS-17660: Disable rcu_expedited after node has finished booting

### PR DESCRIPTION
**Pull request by fontivan**
- This is accomplished by setting "rcu_normal" to 1

### CODE REVIEW

**Comment by fontivan** [comment]
Although I have tested this manually by oc apply'ing the generated MC I want to verify it works straight from installation before allowing this to merge

**Comment by imiller0** [comment]
Note that your commit message needs to be prefixed with "ztp: ...."

**Comment by fontivan** [comment]
Finished retesting this morning with installation, all looking good from my perspective

**Review by imiller0 — APPROVED** [review]
/lgtm

**Pull request merged**
