### PR TITLE
ztp/multinode policy reduction

### PR DESCRIPTION
**Pull request by lack**
Reduce policy count for multi-node examples

### CODE REVIEW

**Comment by pixelsoccupied** [comment]
/lgmt the commit for reducing total number of [policies](https://github.com/openshift-kni/cnf-features-deploy/pull/872/commits/291b7892cc79e5a2983b8624555c8e54616fe726). Do test it out on a live cluster (just in case)

**Comment by lack** [comment]
/unhold
Re-asserting @pixelsoccupied 's /lgtm after testing.

**Pull request merged**
