### PR TITLE
cnf-tests: update submodules

### PR DESCRIPTION
**Pull request by shajmakh**
Update submodules of cnf-tests to point to the latest commits, by running `git submodule update --remote`.

### CODE REVIEW

**Comment by ffromani** [comment]
/approve

once ready, we want this bump

**Comment by liornoy** [comment]
> /approve
> 
> once ready, we want this bump

what do you mean by "once ready"?

**Comment by ffromani** [comment]
> > /approve
> > once ready, we want this bump
> 
> what do you mean by "once ready"?

image

**Comment by MarSik** [comment]
/override ci/prow/e2e-gcp-ovn

We are changing how the CI works and some pieces are broken due to that.

**Comment by SchSeba** [comment]
@MarSik should we wait for the CI to work just to validate we didn't introduce any new issue?
or maybe just bump the compute project I can see also metallb and sriov where updated

**Pull request merged**
