### PR TITLE
ignore jetbrains and macos auto generated folders and files

### PR DESCRIPTION
**Pull request by pixelsoccupied**
/cc @lack

### CODE REVIEW

**Comment by pixelsoccupied** [comment]
/override ci/prow/e2e-gcp-ovn

minor update to .gitignore (job fail is irrelevant)

**Comment by pixelsoccupied** [comment]
oops @lack could you run `/override ci/prow/e2e-gcp-ovn` ?

**Review by nishant-parekh — APPROVED** [review]

**Pull request merged**
