### PR TITLE
vendor: Update vendor PAO dependencies

### PR DESCRIPTION
**Pull request by shajmakh**
-Add latency test cases
-Add RT kernel check before checking rcu existence
-Fix netqueues test

### CODE REVIEW

**Comment by Tal-or** [comment]
@shajmakh I reviewed and it looks ok, but I don't have permission to approve.
@MarSik could you please give a review, no one else is available today.

**Comment by shajmakh** [comment]
> @shajmakh I reviewed and it looks ok, but I don't have permission to approve.
> @MarSik could you please give a review, no one else is available today.

Thanks a lot ! I appreciate it !

**Pull request merged**
