### PR TITLE
[release-4.13] Bug OCPBUGS-13313: Backport cpu partitioning siteconfig

### PR DESCRIPTION
**Pull request by eggfoobar**
PR back ports https://github.com/openshift-kni/cnf-features-deploy/pull/1441 and https://github.com/openshift-kni/cnf-features-deploy/pull/1497

/assign @imiller0

### CODE REVIEW

**Comment by imiller0** [comment]
/unhold
4.13 GA artifacts are built. Backport can merge for z-stream.

**Comment by imiller0** [comment]
Just to confirm: If the user continues to use cpuset (and not cpuPartitioningMode) in their SiteConfig the tool will continue to generate the MachineConfigs. In this case workload partitioning continues to be enabled "the old way" and there is no actual impact, correct?

**Comment by eggfoobar** [comment]
That's correct, because of this logic below we still get the old way for SNO and then you can go down the new path with techpreview on 4.13 for non SNO deployments. We also do have some unit tests in place to that will validate that behavior.  https://github.com/openshift-kni/cnf-features-deploy/blob/8d4e1d7b59e35e9bc8792e0440df105d9534b383/ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go#L424-L444

**Review by imiller0 — COMMENTED** [review]
/lgtm

**Review by imiller0 — APPROVED** [review]

**Pull request merged**
