### PR TITLE
Upgrade SCTP machineconfig to ignition v3.1.0

### PR DESCRIPTION
**Pull request by alosadagrande**
Update the SCTP MC to the latest ignition version.

Signed-off-by: Alberto Losada <alosadag@redhat.com>

### CODE REVIEW

**Comment by fedepaol** [comment]
Thanks for this PR!
Let's see if CI is happy

**Comment by yuvalk** [comment]
why is this important and should we do that to other MCs we have?

**Comment by SchSeba** [comment]
@fedepaol do we still need this one??

**Comment by SchSeba** [comment]
closing this one

/close

**Pull request closed without merging**
