### PR TITLE
Bump sriov and machine config operator

### PR DESCRIPTION
**Pull request by SchSeba**
this commit update the sriov operator to support the api
change introduce in the operator-sdk bump to v1

for this I also need to update the machine config operator
to support the latest render changes in the sriov project

Signed-off-by: Sebastian Sch <sebassch@gmail.com>

### CODE REVIEW

**Comment by fedepaol** [comment]
This was covered in https://github.com/openshift-kni/cnf-features-deploy/pull/375
We can go with this first, and change the other one.
@SchSeba in that case we need to add the missing test description, see failing ci

**Comment by SchSeba** [comment]
Thanks for pointing this out!
can you please take another look?

**Comment by fedepaol** [comment]
@SchSeba please rebase this

**Comment by SchSeba** [comment]
@fedepaol done

**Comment by fedepaol** [comment]
@SchSeba this needs rebase

**Pull request merged**
