### PR TITLE
infra: Add gatekeeper to tested features

### PR DESCRIPTION
**Pull request by mmirecki**

### CODE REVIEW

**Comment by yuvalk** [comment]
see #590 
the problem was there was no suitable gatekeeper in redhat-operators for 4.9

**Comment by SchSeba** [comment]
Hi @mmirecki can you please rebase?

**Comment by SchSeba** [comment]
Both lanes failed on a know issue in crio not related to this PR content.
All the gatekeeper tests are green.

```
[91m[1mSummarizing 1 Failure:[0m

[91m[1m[Fail] [0m[90m[rfe_id:27363][performance] CPU Management [0m[0mwhen pod runs with the CPU load balancing runtime class [0m[91m[1m[It] [test_id:32646] should disable CPU load balancing for CPU's used by the pod [0m
[37m/go/src/github.com/openshift-kni/cnf-features-deploy/vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go:323[0m
```

/override ci/prow/e2e-gcp
/override ci/prow/e2e-gcp-ovn

/cherry-pick release-4.9

**Review by SchSeba — COMMENTED** [review]
/lgtm
/approve

**Comment by SchSeba** [comment]
@mmirecki can you please cherry-pick this to 4.9 and then 4.8?

**Pull request merged**
