### PR TITLE
Bug 2051540: cnf-tests: filter main CPU's thread siblings under the cyclic test

### PR DESCRIPTION
**Pull request by Tal-or**
Signed-off-by: Talor Itzhak <titzhak@redhat.com>

### CODE REVIEW

**Comment by Tal-or** [comment]
/hold cancel
tested manually

**Comment by cynepco3hahue** [comment]
@SchSeba Do we have some progress with failures
```

[Fail] sro Apply the special resource CR to build the OOT driver [It] should have a oot driver imagestream built 
/go/src/github.com/openshift-kni/cnf-features-deploy/cnf-tests/testsuites/e2esuite/sro/sro.go:184
[Fail] sro Apply the special resource CR to build the OOT driver [It] should have the driver built inside the container 
/go/src/github.com/openshift-kni/cnf-features-deploy/cnf-tests/testsuites/e2esuite/sro/sro.go:189
```
?

**Comment by cynepco3hahue** [comment]
Failed on
```
Summarizing 2 Failures:
[Fail] sro Apply the special resource CR to build the OOT driver [It] should have a oot driver imagestream built 
/go/src/github.com/openshift-kni/cnf-features-deploy/cnf-tests/testsuites/e2esuite/sro/sro.go:184
[Fail] sro Apply the special resource CR to build the OOT driver [It] should have the driver built inside the container 
/go/src/github.com/openshift-kni/cnf-features-deploy/cnf-tests/testsuites/e2esuite/sro/sro.go:189
```
/override ci/prow/e2e-gcp-ovn

**Pull request merged**
