### PR TITLE
Bug 1895871: DPDK test: don't backup and create sriov configuration in regular mode.

### PR DESCRIPTION
**Pull request by fedepaol**
In regular mode it's safe to assume there are no extra configurations in the cluster. Not having to backup and restore will make the test cycle faster, and will reduce the chance of not restoring the configuration because of errors in the middle.

### CODE REVIEW

**Comment by fedepaol** [comment]
/hold
still to validate

**Review by SchSeba — APPROVED** [review]
/lgtm

/hold

please remove the hold after validation

**Review by SchSeba — APPROVED** [review]
/lgtm

/hold cancel

**Pull request merged**
