### PR TITLE
infra: Support ARM64 platform in jobs

### PR DESCRIPTION
**Pull request by sshnaidm**

### CODE REVIEW

**Comment by sshnaidm** [comment]
result with this patch: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/53264/rehearse-53264-pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests/1802731535330185216
from PR https://github.com/openshift/release/pull/53264

**Review by SchSeba — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
