### PR TITLE
remove runlevel 1

### PR DESCRIPTION
**Pull request by yuvalk**
- features: remove `run-level: 1` from sriov
- ztp: remove `run-level: 1` from ztp

### CODE REVIEW

**Review by nishant-parekh — APPROVED** [review]

**Comment by zeeke** [comment]
/lgtm

No SRIOV test can be triggered on this PR. We'll see if some test needed run-level:1 during [next nightly](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g)

**Comment by SchSeba** [comment]
Hi @yuvalk can you please explain why we remove this? :)

**Comment by SchSeba** [comment]
failing test is not related

/override ci/prow/e2e-gcp-ovn
/lgtm
/approve

**Pull request merged**
