### PR TITLE
infra: Update openshift-ci base image to fedora 37

### PR DESCRIPTION
**Pull request by bartwensley**
Signed-off-by: Bart Wensley <bwensley@redhat.com>

### CODE REVIEW

**Comment by ffromani** [comment]
looks like the fedora 34 tag was removed from https://quay.io/repository/fedora/fedora?tab=tags
in general we should bump the base image periodically to be up to date with tooling, so I'm OK with this change
I wonder (and I'll check separately) if similar repos have the same issue

**Comment by imiller0** [comment]
/override ci/prow/ci ci/prow/e2e-aws-ran-profile ci/prow/e2e-gcp-ovn ci/prow/images

**Pull request merged**
