### PR TITLE
Promote the Performance Profile to v2

### PR DESCRIPTION
**Pull request by marcel-apf**
Will allow behavior change

### CODE REVIEW

**Comment by fromanirh** [comment]
/lgtm
/hold
cc @fedepaol (please loop in anyone else that may be interested)

**Comment by fromanirh** [comment]
CI failure is legit:
```
 The test [rfe_id:27368][performance] Verify API Conversions [test_id:35887] Verifies v1 <-> v1alpha1 conversions do not have a valid description
The test [rfe_id:27368][performance] Verify API Conversions [test_id:35888] Verifies v1 <-> v2 conversions do not have a valid description
2020/10/27 09:03:00 Failed to fill missing descriptions 'Found tests with no description'
/go/src/github.com/openshift-kni/cnf-features-deploy 
```

**Comment by marcel-apf** [comment]
Now we have:
`
[performance][config] Performance configuration
[90m/go/src/github.com/openshift-kni/cnf-features-deploy/vendor/github.com/openshift-kni/performance-addon-operators/functests/0_config/config.go:37[0m
  [91m[1mShould successfully deploy the performance profile [It][0m
  [90m/go/src/github.com/openshift-kni/cnf-features-deploy/vendor/github.com/openshift-kni/performance-addon-operators/functests/0_config/config.go:39[0m

  [91mTimed out after 900.000s.
  Failed creating the performance profile
  Unexpected error:
      <*meta.NoKindMatchError | 0xc0000b0640>: {
          GroupKind: {
              Group: "performance.openshift.io",
              Kind: "PerformanceProfile",
          },
          SearchedVersions: ["v2"],
      }
      no matches for kind "PerformanceProfile" in version "performance.openshift.io/v2"
`

**Comment by marcel-apf** [comment]
Depends on https://github.com/openshift-kni/cnf-features-deploy/pull/349

**Comment by marcel-apf** [comment]
This is just sad, may a problem with the CI?
```
Running gofmt
gofmt -s -l `find . -path ./vendor -prune -o -type f -name '*.go' -print`
/bin/sh: gofmt: command not found
make: *** [Makefile:41: gofmt] Error 127
```

**Comment by fromanirh** [comment]
This is weird:
```
which: no go in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.gimme/versions/go1.13.5.linux.amd64/bin:/go/bin:/go/bin:/go/bin:/go/bin)
No go command available
/go/src/github.com/openshift-kni/cnf-features-deploy
/go/src/github.com/openshift-kni/cnf-features-deploy
make: *** [Makefile:35: functests] Error 1
```
also considering https://github.com/openshift-kni/cnf-features-deploy/pull/350#issuecomment-717430655 , let's check if the base image changed or in general why the basic tooling is suddenly not available before to retest

**Comment by marcel-apf** [comment]
> This is weird:
> 
> ```
> which: no go in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.gimme/versions/go1.13.5.linux.amd64/bin:/go/bin:/go/bin:/go/bin:/go/bin)
> No go command available
> /go/src/github.com/openshift-kni/cnf-features-deploy
> /go/src/github.com/openshift-kni/cnf-features-deploy
> make: *** [Makefile:35: functests] Error 1
> ```
> 
> also considering [#350 (comment)](https://github.com/openshift-kni/cnf-features-deploy/pull/350#issuecomment-717430655) , let's check if the base image changed or in general why the basic tooling is suddenly not available before to retest

How can be anything changed if this PR is based on the same version as https://github.com/openshift-kni/cnf-features-deploy/pull/349 that was just merged, so I assume it did pass the tests?

**Comment by fromanirh** [comment]
> > This is weird:
> > ```
> > which: no go in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.gimme/versions/go1.13.5.linux.amd64/bin:/go/bin:/go/bin:/go/bin:/go/bin)
> > No go command available
> > /go/src/github.com/openshift-kni/cnf-features-deploy
> > /go/src/github.com/openshift-kni/cnf-features-deploy
> > make: *** [Makefile:35: functests] Error 1
> > ```
> > 
> > 
> > also considering [#350 (comment)](https://github.com/openshift-kni/cnf-features-deploy/pull/350#issuecomment-717430655) , let's check if the base image changed or in general why the basic tooling is suddenly not available before to retest
> 
> How can be anything changed if this PR is based on the same version as #349 that was just merged, so I assume it did pass the tests?

because we depend on OCP CI and on their base images (to some extent), and how we build our images on CI, which can change with their own pace and with their own timelines. I'm not claiming this is the cause (can be an issue on our side or a transient error, or something else), but this is something we need to take into account.

**Comment by marcel-apf** [comment]
platform issue, usually solved in 1 hour
/retest

**Review by fromanirh — APPROVED** [review]
/lgtm
/hold
letting @cynepco3hahue review

**Pull request merged**
