### PR TITLE
OCPBUGS-5219: vendor: bump NTO dependencies 20230125

### PR DESCRIPTION
**Pull request by Tal-or**
Signed-off-by: Talor Itzhak <titzhak@redhat.com>

### CODE REVIEW

**Comment by yanirq** [comment]
please update this to point at the last changes if you can

**Comment by Tal-or** [comment]
We can't bump this PR forward, since latest changes are involved with ginkgo v2

**Comment by SchSeba** [comment]
we will do it as part of https://github.com/openshift-kni/cnf-features-deploy/pull/1384

**Comment by Tal-or** [comment]
@SchSeba We need it in order to fix OCPBUGS-5219, I'll change the title.

**Comment by Tal-or** [comment]
After https://github.com/openshift/cluster-node-tuning-operator/pull/535 got merged we need to bump NTO version

**Comment by Tal-or** [comment]
The bump will done as part of https://github.com/openshift-kni/cnf-features-deploy/pull/1384

**Pull request closed without merging**
