### PR TITLE
OCPBUGS-24205: [release-4.14] bump NTO deps

### PR DESCRIPTION
**Pull request by Tal-or**
This bump contains fix for the bug above.

### CODE REVIEW

**Comment by ffromani** [comment]
PTAL: https://github.com/openshift-kni/cnf-features-deploy/pull/1717#issuecomment-1837415504

**Comment by Tal-or** [comment]
> PTAL: [#1717 (comment)](https://github.com/openshift-kni/cnf-features-deploy/pull/1717#issuecomment-1837415504)

@ffromani I don't think @liornoy backport the spilt to 4.14

**Comment by ffromani** [comment]
> > PTAL: [#1717 (comment)](https://github.com/openshift-kni/cnf-features-deploy/pull/1717#issuecomment-1837415504)
> 
> @ffromani I don't think @liornoy backport the spilt to 4.14

I think silly me should drink his coffee BEFORE reviewing PRs. I'll have another look ASAP.

**Comment by SchSeba** [comment]
Hi the failing test related to this change?

```
[38;5;9m[FAIL][0m [0m[rfe_id:27363][performance] CPU Management [38;5;243mwhen pod runs with the CPU load balancing runtime class [38;5;9m[1m[It] [test_id:32646] should disable CPU load balancing for CPU's used by the pod[0m
  [38;5;243m/go/src/github.com/openshift-kni/cnf-features-deploy/vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/cpu_management.go:349[0m
```

**Comment by Tal-or** [comment]
> Hi the failing test related to this change?
> 
> ```
> �[38;5;9m[FAIL]�[0m �[0m[rfe_id:27363][performance] CPU Management �[38;5;243mwhen pod runs with the CPU load balancing runtime class �[38;5;9m�[1m[It] [test_id:32646] should disable CPU load balancing for CPU's used by the pod�[0m
>   �[38;5;243m/go/src/github.com/openshift-kni/cnf-features-deploy/vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/cpu_management.go:349�[0m
> ```

Nope. this is related to other issue, but I recall @mrniranjan already fixed it.

**Comment by Tal-or** [comment]
more updated were add so I bumped again.

**Pull request closed without merging**
