### PR TITLE
Update PAO dependencies

### PR DESCRIPTION
**Pull request by cynepco3hahue**
The PR needed because of the fix to the `pod runs with the CPU load balancing runtime class` test.

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@fedepaol Please review

**Comment by cynepco3hahue** [comment]
@fedepaol @fromanirh Can you please review?

**Review by fromanirh — APPROVED** [review]
looks good, the only thing not completely clear is why this is needed

**Comment by cynepco3hahue** [comment]
> looks good, the only thing not completely clear is why this is needed

Added under the PR description of why the PR needed.

**Pull request merged**
