### PR TITLE
Temporarily disable RT kernel

### PR DESCRIPTION
**Pull request by slintes**
Reason: https://bugzilla.redhat.com/show_bug.cgi?id=1811630

### CODE REVIEW

**Comment by slintes** [comment]
`should be enabled with the single-numa-node policy [It]` - expected, see #108 
`should have RT kernel enabled [It]`  - expected, caused by this change

`Non-guaranteed POD can work on any CPU [It]` - unexpected
`Guaranteed POD should work on isolated cpu [It]` - unexpected

/retest

**Comment by fedepaol** [comment]
/lgtm

Feel free to remove the hold if you get to this before me

**Comment by slintes** [comment]
only the 2 expected failures now

/hold cancel

**Pull request merged**
