### PR TITLE
Changed GK deployment name

### PR DESCRIPTION
**Pull request by evgenLevin**
Deployment was changed in the GK version 0.2.0

### CODE REVIEW

**Comment by cgoncalves** [comment]
/title Bug 2015836: Changed GK deployment name

**Comment by cgoncalves** [comment]
I think backporting https://github.com/openshift-kni/cnf-features-deploy/pull/653 would be best, as Sebastian also suggested in a comment. @mmirecki what do you think?

**Comment by mmirecki** [comment]
> I think backporting #653 would be best, as Sebastian also suggested in a comment. @mmirecki what do you think?

Yes, this will solve all the issues at once

**Comment by SchSeba** [comment]
I think we can close this one no?

**Comment by evgenLevin** [comment]
yes

**Pull request closed without merging**
