### PR TITLE
[release-4.8] cnf-tests: bump PAO vendor

### PR DESCRIPTION
**Pull request by SchSeba**
To bump any feature tests on cnf-test you need to do the following steps:
1.  update the `go.mod` file replaces the sha with the release 
example:

```
fom:
replace (
        github.com/k8snetworkplumbingwg/sriov-network-operator => github.com/openshift/sriov-network-operator v0.0.0-20210805190637-3f3ebe7deb22 // release-4.8
        github.com/openshift-kni/performance-addon-operators => github.com/openshift-kni/performance-addon-operators v0.0.0-20210825143756-776681f670d5 // release-4.8
        github.com/openshift/ptp-operator => github.com/openshift/ptp-operator v0.0.0-20210808104033-dc3817f3d144 // release-4.8
)

to:
replace (
        github.com/k8snetworkplumbingwg/sriov-network-operator => github.com/openshift/sriov-network-operator release-4.8 // release-4.8
        github.com/openshift-kni/performance-addon-operators => github.com/openshift-kni/performance-addon-operators release-4.8 // release-4.8
        github.com/openshift/ptp-operator => github.com/openshift/ptp-operator release-4.8 // release-4.8
)

```

2. run `make deps-update`
3. run `make check-tests-nodesc`
4. add the test description if new test exist from the update
5. make generate-cnf-tests-doc

Signed-off-by: Sebastian Sch <sebassch@gmail.com>

### CODE REVIEW

**Comment by yanirq** [comment]
@SchSeba   please write in the PR description what manual steps you did in case someone else is not familiar with it and could do it as well

**Comment by SchSeba** [comment]
@yanirq done can you please have a look?

**Comment by SchSeba** [comment]
we need this PR I think first

https://github.com/openshift-kni/cnf-features-deploy/pull/671

**Pull request merged**
