### PR TITLE
Fix for labeling worker nodes

### PR DESCRIPTION
**Pull request by dshchedr**
Exclude nodes with 'master' label

### CODE REVIEW

**Comment by davidvossel** [comment]
i think this needs a rebase. It's possible that @fedepaol actually addressed this recently though when he introduced the logic to converge on the worker-cnf machineconfigpool

**Comment by fedepaol** [comment]
The sed expression in the new version already works if we only have one node, so I'd say we can close this.

**Comment by dshchedr** [comment]
> The sed expression in the new version already works if we only have one node, so I'd say we can close this.

But we still need to exclude "master" nodes if they also have "worker" label.

**Pull request merged**
