### PR TITLE
ztp: removing userData temporarily to enable testing for ztp

### PR DESCRIPTION
**Pull request by nishant-parekh**
Underlying implementation will updated and added back tracked under https://github.com/openshift-kni/cnf-features-deploy/issues/619

### CODE REVIEW

**Review by serngawy — APPROVED** [review]

**Review by vitus133 — APPROVED** [review]

**Comment by ijolliffe** [comment]
/retest

failure log points to performance operator in running state issue, nothing changed related to performance operator in this commit

**Pull request merged**
