### PR TITLE
[release-4.6] Update PAO dependencies

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
/lgtm
/hold
giving time to other reviewers to chime in.

**Comment by fedepaol** [comment]
@cynepco3hahue any reason why it was not cherry picked to 4.7 but only 4.6?

**Comment by cynepco3hahue** [comment]
It was :) https://github.com/openshift-kni/cnf-features-deploy/pull/431

**Pull request merged**
