### PR TITLE
cnf-tests: update submodules

### PR DESCRIPTION
**Pull request by shajmakh**
update to the latest version of submodules repos by running:
1. git submodule update --init --force
2. git submodule update --remote

### CODE REVIEW

**Comment by shajmakh** [comment]
/hold 
NTO is not shown as updated

**Comment by shajmakh** [comment]
blocking: https://github.com/openshift/release/pull/48512

**Review by MarSik — APPROVED** [review]
/lgtm

**Review by MarSik — APPROVED** [review]

**Comment by shajmakh** [comment]
@fedepaol May you approve please?

**Comment by SchSeba** [comment]
should we use this? https://github.com/openshift-kni/cnf-features-deploy/pull/1881

**Comment by shajmakh** [comment]
closing in favor #1881

**Pull request closed without merging**
