### PR TITLE
cnf-tests: multinetworkpolicy typo fix in validationsuit

### PR DESCRIPTION
**Pull request by Missxiaoguo**
Jira: [CNF-2983](https://issues.redhat.com//browse/CNF-2983)
Signed-off-by: Angie Wang <angwang@redhat.com>

### CODE REVIEW

**Comment by lack** [comment]
I think you need to run a script to regenerate some of the documentation too...

**Comment by Missxiaoguo** [comment]
> I think you need to run a script to regenerate some of the documentation too...

Yeah, I am going to take a look the ci job. Let's see how ran-profile job works this time.

**Comment by Missxiaoguo** [comment]
The ran profile CI worked finally. Yay ~ Updated the docs for ci job.

**Review by lack — APPROVED** [review]

**Pull request merged**
