### PR TITLE
cnf-tests: bond cni on over macvlan test

### PR DESCRIPTION
**Pull request by mmirecki**
Adding test verifying that a pod with a bond interface over two macvlan interfaces is created correctly

### CODE REVIEW

**Comment by mmirecki** [comment]
cc @fedepaol

**Comment by fedepaol** [comment]
As a secodn thought, would you mind extending the commit message?

**Comment by fedepaol** [comment]
> > New changes are detected. LGTM label has been removed.
> 
> Updated

typo: inerfaces

**Review by SchSeba — COMMENTED** [review]
@mmirecki can you please add all the needed information into the reporter please

**Pull request merged**
