### PR TITLE
ztp: Update ZTP gitops documentation to reflect the new TALO-based policy application

### PR DESCRIPTION
**Pull request by lack**
Signed-off-by: Jim Ramsay <jramsay@redhat.com>

/cc @imiller0 @serngawy

### CODE REVIEW

**Comment by lack** [comment]
/retest
Come on, this just adjusts a README.md!  Why do we even have this test?

**Comment by lack** [comment]
I snuck in a couple more doc edits here that came out of a discussion I had with our QE team, just to clean up the PGT and SiteConfig example consistency.

**Review by serngawy — COMMENTED** [review]
sounds good to me, would u squash the commits.

**Comment by lack** [comment]
> sounds good to me, would u squash the commits.

I think they are 3 logically distinct  changes - One updates documentation, one fixes an error in the examples, the last adds comments to SiteConfig...

**Pull request merged**
