### PR TITLE
Updated PAO dependencies to reflect folder layout changes

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@fromanirh @fedepaol Update PAO master dependencies include the fix for the broken bitbucket dependency

**Comment by cynepco3hahue** [comment]
@fedepaol @fromanirh Please review

**Review by fromanirh — COMMENTED** [review]
/lgtm
this should probably have been a followup of the PAO PR which did the operator-sdk v1 transition. let's think about it next time

**Comment by fromanirh** [comment]
/hold
waiting for @fedepaol approval

**Pull request merged**
