### PR TITLE
Update performance deps to the latest release-4.5

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by SchSeba** [comment]
@cynepco3hahue can you please open this base on master and then we can create a cherry-pick of it?

**Comment by SchSeba** [comment]
@cynepco3hahue I can also see a failure to build the image.

```
Failed to compile functests:

# github.com/openshift-kni/cnf-features-deploy/functests
package github.com/openshift-kni/cnf-features-deploy/functests_test
	imports github.com/openshift-kni/performance-addon-operators/functests/1_performance
	imports github.com/openshift-kni/performance-addon-operators/functests/utils/client
	imports github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1: cannot find package "." in:
	/go/src/github.com/openshift-kni/cnf-features-deploy/vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1
FAIL	github.com/openshift-kni/cnf-features-deploy/functests [setup failed]
FAIL

make: *** [test-bin] Error 1
```

**Comment by cynepco3hahue** [comment]
@SchSeba Hm the master will vendor master dependencies and 4.5 should vendor 4.5 dependencies, the vendor folder can be different.

**Comment by fedepaol** [comment]
This can be closed because of https://github.com/openshift-kni/cnf-features-deploy/pull/226 right?

**Comment by cynepco3hahue** [comment]
@fedepaol yep, it still strange why it brings such amount of dependencies. Probably it does not use `mod=vendor` under the CI, when I use `go1.14.2` that uses it by default.

**Comment by cynepco3hahue** [comment]
@fedepaol Hm after running `go clean --modcache` I see the same big change.

**Pull request closed without merging**
