### PR TITLE
operator: move to 4.9

### PR DESCRIPTION
**Pull request by fromanirh**
Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
looks like we still pull from docker?
```
 time="2021-07-21T08:32:09Z" level=warning msg="failed, retrying in 5s ... (1/2). Error: Error initializing source docker://openshift/origin-release:golang-1.16: Error reading manifest golang-1.16 in docker.io/openshift/origin-release: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
time="2021-07-21T08:32:44Z" level=warning msg="failed, retrying in 5s ... (2/2). Error: Error initializing source docker://openshift/origin-release:golang-1.16: Error reading manifest golang-1.16 in docker.io/openshift/origin-release: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" 
```

**Comment by cynepco3hahue** [comment]
@fromanirh You need to update test descriptions
```
The test [rfe_id:27368][performance] Pre boot tuning adjusted by tuned  [test_id:42696][crit:medium][vendor:cnf-qe@redhat.com][level:acceptance] Stalld runs in higher priority than ksoftirq and rcu{c,b} does not have a valid description
2021/07/23 08:00:22 Failed to fill missing descriptions 'Found tests with no description'
```

**Comment by fromanirh** [comment]
> @fromanirh You need to update test descriptions
> 
> ```
> The test [rfe_id:27368][performance] Pre boot tuning adjusted by tuned  [test_id:42696][crit:medium][vendor:cnf-qe@redhat.com][level:acceptance] Stalld runs in higher priority than ksoftirq and rcu{c,b} does not have a valid description
> 2021/07/23 08:00:22 Failed to fill missing descriptions 'Found tests with no description'
> ```

thanks, on it

**Pull request merged**
