### PR TITLE
vendor: bump NTO dependencies 20221024

### PR DESCRIPTION
**Pull request by Tal-or**
Signed-off-by: Talor Itzhak <titzhak@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
/override ci/prow/e2e-gcp-ovn
failed for unrelated reasons (and perma-failing?). If turns out this PR is faulty, I commit to fix/revert

**Comment by fromanirh** [comment]
/override ci/prow/e2e-gcp-ran-profile
failed for unrelated reasons (and perma-failing?). If turns out this PR is faulty, I commit to fix/revert

**Comment by fromanirh** [comment]
interesting: this worked for me locally:
```
podman build -f cnf-tests/Dockerfile .
```

**Comment by Tal-or** [comment]
> interesting: this worked for me locally:
> 
> ```
> podman build -f cnf-tests/Dockerfile .
> ```

Just for the completes of the discussion the problem is with:
```podman build -f openshift-ci/Dockerfile.tools .```

**Comment by Tal-or** [comment]
depends on #1308

**Comment by fromanirh** [comment]
/override ci/prow/e2e-gcp-ran-profile
red since long time and not blocking anyway, but still

**Pull request merged**
