### PR TITLE
Bug 2035036: ztp: Remove Reboot Recovery script

### PR DESCRIPTION
**Pull request by tliu2021**
Reboot Recovery script has been incorporated into upstream (PAO):
https://github.com/openshift-kni/performance-addon-operators/pull/757

This update removes reboot recovery script from ztp.

Signed-off-by: tliu2021 <tali@redhat.com>

### CODE REVIEW

**Comment by tliu2021** [comment]
/hold
Waiting for PAO changes to be merged.

**Comment by lack** [comment]
@tliu2021 I think we should close this for now - The upstream code has moved and will take a lot more work to get right before we're ready to discontinue the ZTP version of this.

**Pull request closed without merging**
