### PR TITLE
cnf-tests: call klog.Infof function

### PR DESCRIPTION
**Pull request by Tal-or**
Signed-off-by: Talor Itzhak <titzhak@redhat.com>

### CODE REVIEW

**Review by nishant-parekh — APPROVED** [review]

**Comment by fromanirh** [comment]
/override ci/prow/e2e-gcp-ovn
/override ci/prow/e2e-gcp-ran-profile
this PR can't break either of these two lanes

**Comment by Tal-or** [comment]
> /override ci/prow/e2e-gcp-ovn /override ci/prow/e2e-gcp-ran-profile this PR can't break either of these two lanes

Thanks!

**Pull request merged**
