### PR TITLE
ztp: Downgrade MCO to an ignition version v3.2.0

### PR DESCRIPTION
**Pull request by zeeke**
ZTP must produce MachineConfig resources with ignition version v3.2.0
Since https://github.com/openshift/machine-config-operator/pull/3814, MCO writes v3.4.0 ignition configuration.
https://github.com/openshift/machine-config-operator/commit/63d7be1ef18b86826b47c61172c7a9dc7c2b6de1 is the commit just before the culprit one.

Also, machine-config-operator@63d7be1ef18b86826b47c61172c7a9dc7c2b6de1
has a transitive dependency to `github.com/Microsoft/hcsshim@v0.8.7` that cause
a `go mod tidy` error:

```
github.com/Microsoft/hcsshim@v0.8.7 requires
k8s.io/kubernetes@v1.13.0 requires
k8s.io/endpointslice@v0.0.0: reading k8s.io/endpointslice/go.mod at revision v0.0.0: unknown revision v0.0.0
```
which is fixed in v0.8.8 by https://github.com/microsoft/hcsshim/pull/783

cc @jzding, @sabbir-47 , @lack , @imiller0

### CODE REVIEW

**Comment by lack** [comment]
/lgtm

This is a band-aid, though. @sabbir-47 Can you link to the Jira item where we'll be doing a longer-term fix for this, once you've created it?

**Comment by zeeke** [comment]
I need to rebase as some ignition v3.4.0 references have been introduced in:
- https://github.com/openshift-kni/cnf-features-deploy/pull/1659

**Comment by sabbir-47** [comment]
For the longer term fix, the story created: https://issues.redhat.com/browse/CNF-11361

**Comment by zeeke** [comment]
/override ci/prow/e2e-aws-ci-tests

```
Metallb Operator E2E Suite: [It] metallb MetalLB deploy should have frr-k8s pods in running state 
```
not related to this PR

**Comment by zeeke** [comment]
@sabbir-47 , @lack please, take another look

**Comment by zeeke** [comment]
AWS related jobs are temporarily failing due to https://redhat-internal.slack.com/archives/CFUGK0K9R/p1712602383028359 

/override ci/prow/e2e-aws-ci-tests

**Pull request merged**
