### PR TITLE
Bump operators to 4.7

### PR DESCRIPTION
**Pull request by SchSeba**
Signed-off-by: Sebastian Sch <sebassch@gmail.com>

### CODE REVIEW

**Comment by yuvalk** [comment]
unfortunatly I think we need a similar fix in the release-4.7 branch

**Comment by SchSeba** [comment]
4.7 one

https://github.com/openshift-kni/cnf-features-deploy/pull/475

**Comment by SchSeba** [comment]
Let's use the 4.7 and before we branch out for 4.8 we change the operator's version as there are no 4.8 operators( OCP 4.8 is not released yet)

**Comment by yuvalk** [comment]
/override ci/prow/ci
/override ci/prow/e2e-gcp
/override ci/prow/e2e-gcp-ovn
/override ci/prow/e2e-gcp-ran-profile
/override ci/prow/images

because they were all previously passing and we just changed the commit msg

**Pull request merged**
