### PR TITLE
Remove ztp-playbooks from cnf-features-deploy

### PR DESCRIPTION
**Pull request by yrobla**
This will be moved to ztp-cluster-deploy repo

Signed-off-by: Yolanda Robla <yroblamo@redhat.com>

### CODE REVIEW

**Comment by yuvalk** [comment]
even after this PR, there are still some files under `ztp-playbooks` directory (like the install-ai-operator)
assuming this is intentional (is it?)
maybe you do want to keep the README file too?

**Review by serngawy — APPROVED** [review]

**Pull request merged**
