### PR TITLE
WIP Add script to analyze reboots

### PR DESCRIPTION
**Pull request by rcarrillocruz**
@lack @tliu2021 @alosadagrande I don't know where to put this, if you have better ideas let me know.
Also, please comment things as you see fit, I figure it's better to drive it in a PR than on a gdoc .

### CODE REVIEW

**Review by tliu2021 — COMMENTED** [review]
As the rendered MachineConfig(MC) object contains all previously applied MC objects, it would be hard for the user to find out which MC triggered the reboot. It would be nice to show the diff between each reboot.

**Comment by rcarrillocruz** [comment]
> As the rendered MachineConfig(MC) object contains all previously applied MC objects, it would be hard for the user to find out which MC triggered the reboot. It would be nice to show the diff between each reboot.

Can you expand on showing diff? Which two things should be diffed, the one shown the logs against...

**Comment by tliu2021** [comment]
@rcarrillocruz For example, find the first boot rendered MC object “rendered-master-aed6f420dea74d85a71e857fc5d280f7” from the following logs
Jan 12 14:53:46 cnfocto1.ptp.lab.eng.bos.redhat.com root[3981]: machine-config-daemon[3796]: initiating reboot: Completing firstboot provisioning to rendered-master-aed6f420dea74d85a71e857fc5d280f7

Then get the second reboot rendered MC objects “rendered-master-1dd38629a8e669a5bf61f1509bab354b” from the logs shown below:
Jan 12 15:29:32 cnfocto1.ptp.lab.eng.bos.redhat.com root[145716]: machine-config-daemon[12144]: initiating reboot: Node will reboot into config rendered-master-1dd38629a8e669a5bf61f1509bab354b

The difference between the two files would show the new configurations that triggered the second reboot.

**Comment by rcarrillocruz** [comment]
So what you are saying is getting the history of all the reboot rendered MCs and diff them consecutively. Ok, thanks.

**Pull request closed without merging**
