### PR TITLE
Changed the name of "sriov fec" tests to  "fec"

### PR DESCRIPTION
**Pull request by evgenLevin**
"sriov fec" test had in it`s name the same name of another operator "sriov", which leads to incorrec operation of FEATURES variable.

### CODE REVIEW

**Comment by evgenLevin** [comment]
@fedepaol Changed to SR-IOV. "SRIOV" also matched by FEATURES=sriov

**Comment by fedepaol** [comment]
> @fedepaol Changed to SR-IOV. "SRIOV" also matched by FEATURES=sriov

Can we just call it fec? I think it's less confusing. WDYT?

**Comment by evgenLevin** [comment]
> > @fedepaol Changed to SR-IOV. "SRIOV" also matched by FEATURES=sriov
> 
> Can we just call it fec? I think it's less confusing. WDYT?

Operator called `sriov-fec`. But as for me fec much clearer. Change to "fec"?

**Comment by fedepaol** [comment]
> > > @fedepaol Changed to SR-IOV. "SRIOV" also matched by FEATURES=sriov
> > 
> > 
> > Can we just call it fec? I think it's less confusing. WDYT?
> 
> Operator called `sriov-fec`. But as for me fec much clearer. Change to "fec"?

Yes

**Comment by evgenLevin** [comment]
> > > > @fedepaol Changed to SR-IOV. "SRIOV" also matched by FEATURES=sriov
> > > 
> > > 
> > > Can we just call it fec? I think it's less confusing. WDYT?
> > 
> > 
> > Operator called `sriov-fec`. But as for me fec much clearer. Change to "fec"?
> 
> Yes

Done

**Comment by fedepaol** [comment]
Looks good, can you provide a short description in the commit message to explain the reason of the change?

**Comment by evgenLevin** [comment]
> Looks good, can you provide a short description in the commit message to explain the reason of the change?

added

**Pull request merged**
