### PR TITLE
Bump sriov and ptp operator using release 4.9 branch

### PR DESCRIPTION
**Pull request by SchSeba**
Signed-off-by: Sebastian Sch <sebassch@gmail.com>

### CODE REVIEW

**Comment by SchSeba** [comment]
the failed test are not related to this change

/override ci/prow/e2e-gcp-ovn

**Comment by yuvalk** [comment]
yes, but if you override, then this change doesnt get tested.

**Comment by yuvalk** [comment]
we have these failures, cross-wide, I think we need to spend some time investigating more deeply why they happen 
I'm on it with @fedepaol

**Pull request merged**
