### PR TITLE
[release-4.14] tools: Add HTML converting to code and make true by default

### PR DESCRIPTION
**Pull request by sshnaidm**
This is a cherry-pick of #1750

### CODE REVIEW

**Comment by sshnaidm** [comment]
Tests results example: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-kni_cnf-features-deploy/1786/pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests/1749161908369362944/artifacts/e2e-aws-ci-tests/e2e-aws-ci-tests/artifacts/cnftests.html

**Comment by SchSeba** [comment]
wait for https://github.com/openshift-kni/cnf-features-deploy/pull/1778 to be merge first

**Comment by sshnaidm** [comment]
@SchSeba 4.15 is merged

**Comment by sshnaidm** [comment]
the results:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-kni_cnf-features-deploy/1786/pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests/1767569108775211008/artifacts/e2e-aws-ci-tests/e2e-aws-ci-tests/artifacts/cnftests.html

@SchSeba can we merge it?

**Pull request merged**
