### PR TITLE
cnf-tests: Remove trailing space in test name

### PR DESCRIPTION
**Pull request by sshnaidm**
The trailing space confuses results parsing and just ain't nice.

### CODE REVIEW

**Review by swatisehgal — APPROVED** [review]
/lgtm

**Comment by yuvalk** [comment]
these better be removed at the source
for example:
https://github.com/openshift/cluster-node-tuning-operator/blob/master/test/e2e/performanceprofile/functests/1_performance/hugepages.go#L62

then update the vendored content
and regenerate the e2e.json and TESTLIST.md

**Comment by sshnaidm** [comment]
> these better be removed at the source for example: https://github.com/openshift/cluster-node-tuning-operator/blob/master/test/e2e/performanceprofile/functests/1_performance/hugepages.go#L62
> 
> then update the vendored content and regenerate the e2e.json and TESTLIST.md

Opened https://github.com/openshift/cluster-node-tuning-operator/pull/540

**Review by SchSeba — COMMENTED** [review]
/hold

@sshnaidm you can't change the vendor folder. this need to be updated in the u/s repo and then update the go mod here

**Pull request closed without merging**
