### PR TITLE
cnf-tests: remove numaresources-operator tests

### PR DESCRIPTION
**Pull request by liornoy**
Migrating cnf-tests to ginkgo/v2 requires bumping
the imported projects, whereas the NROP code changed
massively since the initial integration.

This commit removes the NROP tests for now,
for the sake of merging the ginkgo/v2 bump.

### CODE REVIEW

**Comment by ffromani** [comment]
/lgtm
/approve
I'd have sent the commit in the reverse order - first remove the code consuming the deps, then remove the (no longer used deps).

**Comment by ffromani** [comment]
/lgtm cancel
please don't comment dead code: delete it. When resubmit, please reorder commits (xref: https://github.com/openshift-kni/cnf-features-deploy/pull/1405#issuecomment-1434285877)

**Comment by ffromani** [comment]
the failure in the `images` lane is legit:
```
 [7/7] STEP 22/28: COPY tools/numaresources/pause /pause
[7/7] STEP 23/28: COPY --from=builder /go/src/github.com/o...ni/cnf-features-deploy/cnf-tests/bin/numacell /bin/numacell
error: build error: error building at STEP "COPY --from=bu...s-deploy/cnf-tests/bin/numacell": no such file or directory 
```
we need to remove these bits from the tree as well.

**Comment by liornoy** [comment]
> the failure in the `images` lane is legit:
> 
> ```
>  [7/7] STEP 22/28: COPY tools/numaresources/pause /pause
> [7/7] STEP 23/28: COPY --from=builder /go/src/github.com/o...ni/cnf-features-deploy/cnf-tests/bin/numacell /bin/numacell
> error: build error: error building at STEP "COPY --from=bu...s-deploy/cnf-tests/bin/numacell": no such file or directory 
> ```
> 
> we need to remove these bits from the tree as well.

what do you mean by "remove from the tree" ?

**Comment by liornoy** [comment]
I just saw I left "tools/numaresources/pause" inside. removed. thanks

**Comment by ffromani** [comment]
/retest

because
```
 ERRO[2023-02-19T14:28:47Z] Some steps failed:                           
ERRO[2023-02-19T14:28:47Z] 
  * could not run steps: step [release:latest] failed: failed to get CLI image: unable to find the 'cli' image in the provided release image: unable to create pod: timed out waiting for the condition 
```

**Comment by ffromani** [comment]
> > the failure in the `images` lane is legit:
> > ```
> >  [7/7] STEP 22/28: COPY tools/numaresources/pause /pause
> > [7/7] STEP 23/28: COPY --from=builder /go/src/github.com/o...ni/cnf-features-deploy/cnf-tests/bin/numacell /bin/numacell
> > error: build error: error building at STEP "COPY --from=bu...s-deploy/cnf-tests/bin/numacell": no such file or directory 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > we need to remove these bits from the tree as well.
> 
> what do you mean by "remove from the tree" ?

I mean remove the relevant source code references from the `cnf-tests` source code tree (aliases: codebase, checkout...)

**Comment by SchSeba** [comment]
from my side this lgtm I will let @ffromani to mark it

**Comment by ffromani** [comment]
/override ci/prow/e2e-gcp-ovn
failures in the lane are unrelated to NROP tests (or lack thereof)

**Pull request merged**
