### PR TITLE
[release-4.9] ztp: CNF-3661 Reduce number of policies

### PR DESCRIPTION
**Pull request by imiller0**
cherry-pick of d1e51ff0cba7733974ae264474df0f3ee663adce with addition to
pull PAO subscription into config-policy

### CODE REVIEW

**Comment by imiller0** [comment]
Manual cherry-pick from PR 836.

**Review by serngawy — COMMENTED** [review]
Not sure, if we can cherry-pick this to 4.9. It is a massive change to all policies.

**Comment by imiller0** [comment]
@serngawy do you still have concerns over merging this change?

**Comment by serngawy** [comment]
> @serngawy do you still have concerns over merging this change?

Did you ran through the upgrade process from old policies names to the new policies names ?

**Comment by imiller0** [comment]
Old release. Closing...

**Pull request closed without merging**
