### PR TITLE
infra: Pin packages for go version dependency

### PR DESCRIPTION
**Pull request by imiller0**
Working to fix CI failures. Many thanks to @fromanirh for the fix.  

Signed-off-by: Ian Miller <imiller@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
/lgtm
/approve
We need to review the prow config setting. It seems we're NOT testing HEAD+PR applied, but current HEAD, hence lanes are still failing even if this PR works (tested locally). This behavior could be something we want or something that sneaked in unintentionally.

**Comment by fromanirh** [comment]
I recommend to merge this PR even with lanes failing and monitor right after with any other test PR. The next one after this merged should work. If it is not the case, send another fix or revert this one.

**Comment by fromanirh** [comment]
> I recommend to merge this PR even with lanes failing and monitor right after with any other test PR. The next one after this merged should work. If it is not the case, send another fix or revert this one.

This PR is a good testbed: https://github.com/openshift-kni/cnf-features-deploy/pull/1302

**Comment by imiller0** [comment]
To unblock current CI we are going to try pinning ginkgo and gomega (this PR) in the short term while looking at the bump to go 1.18.

**Pull request merged**
