### PR TITLE
cnf-tests: [release-4.13] Modify k8s reporter

### PR DESCRIPTION
**Pull request by liornoy**
cherry-pick of #1617 
-------------------------------
To improve debugability, This PR bumps the k8s reporter to v1.0.4
And moves the call for the dump function into the FailHandler
to catch the logs before the cleanup after each test.

### CODE REVIEW

**Comment by liornoy** [comment]
Rebased with the latest 4.13 merged commits to pass the CI.

**Review by SchSeba — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
