### PR TITLE
OCPBUGS-33527: ztp: Update ice-dplls tuning to SCHED_FIFO 10

### PR DESCRIPTION
**Pull request by aneeshkp**
[OCPBUGS-33527](https://issues.redhat.com/browse/OCPBUGS-33527)
Update ice-dplls tuning to SCHED_FIFO 10

### CODE REVIEW

**Review by josephdrichard — APPROVED** [review]
/lgtm

**Review by nishant-parekh — APPROVED** [review]
/lgtm

**Pull request merged**
