### PR TITLE
Use dpdk 18.11 in release 4.5 branch

### PR DESCRIPTION
**Pull request by SchSeba**
This PR change the dpdk version to 18.11

Signed-off-by: Sebastian Sch <sebassch@gmail.com>

### CODE REVIEW

**Comment by SchSeba** [comment]
/hold

Need to validate it

**Comment by fedepaol** [comment]
/hold
Feel free to remove the hold

**Comment by SchSeba** [comment]
validated

```
sh-4.2# ./build.sh 
make: Entering directory `/opt/app-root/src/cnf-features-deploy/tools/s2i-dpdk/test/test-app/test-pmd'
  CC testpmd.o
  CC parameters.o
  CC cmdline.o
  CC cmdline_flow.o
  CC cmdline_mtr.o
  CC cmdline_tm.o
  CC config.o
  CC iofwd.o
  CC macfwd.o
  CC macswap.o
  CC flowgen.o
  CC rxonly.o
  CC txonly.o
  CC csumonly.o
  CC icmpecho.o
  CC noisy_vnf.o
  CC bpf_cmd.o
  CC util.o
  CC softnicfwd.o
  LD testpmd
  INSTALL-APP testpmd
  INSTALL-MAP testpmd.map
make: Leaving directory `/opt/app-root/src/cnf-features-deploy/tools/s2i-dpdk/test/test-app/test-pmd'
build done
```

/hold cancel

**Pull request merged**
