### PR TITLE
cnf-tests: Use the built-in oc kustomize (4.13 backport)

### PR DESCRIPTION
**Pull request by liornoy**
Use the built-in `oc kustomize` instead of downloading from github. This change is required to resolve the following error:

Downloading the Kustomize tool
/tmp/shared/cnf/cnf-features-deploy /shared/cnf/cnf-features-deploy Github rate-limiter failed the request.
Either authenticate or wait a couple of minutes.

### CODE REVIEW

**Comment by liornoy** [comment]
Testing patch on openshift/release: https://github.com/openshift/release/pull/39149

**Comment by SchSeba** [comment]
failing tests are not related to the change

/override ci/prow/e2e-gcp-ovn

**Pull request merged**
