### PR TITLE
mcmaker versionbump

### PR DESCRIPTION
**Pull request by lack**
- vendor: bump mcmaker to v0.0.5
- infra: Bump mcmaker in Dockerfile.tools to v0.0.5

This version fixes a bug that is needed by @vitus133 for his chronyd work.

### CODE REVIEW

**Comment by fromanirh** [comment]
/approve
seems safe for master branch

**Comment by SchSeba** [comment]
The one failed is on a performance test that is a know issue in cri-o (not related to this PR)

```
[91m[1mSummarizing 1 Failure:[0m

[91m[1m[Fail] [0m[90m[rfe_id:27363][performance] CPU Management [0m[0mwhen pod runs with the CPU load balancing runtime class [0m[91m[1m[It] [test_id:32646] should disable CPU load balancing for CPU's used by the pod [0m
[37m/go/src/github.com/openshift-kni/cnf-features-deploy/vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go:323[0m
```

/override ci/prow/e2e-gcp
/override ci/prow/e2e-gcp-ovn

**Comment by SchSeba** [comment]
The failing test is not related to the PR I will override the lane

/override ci/prow/e2e-gcp

**Pull request merged**
