### PR TITLE
infra: Checkout sriov repo to PULL_URL HEAD if PULL_URL is from sriov repo

### PR DESCRIPTION
**Pull request by danimjaffe**
In cases where we run BM jobs on sriov-network-operator repo, we would like to build an
operator that the HEAD of the local repo that we build the operator from is the same as the HEAD in the PR that triggered the BM
job.

### CODE REVIEW

**Comment by danimjaffe** [comment]
Needs to first merge: https://github.com/openshift/release/pull/49191

**Comment by liornoy** [comment]
@danimjaffe LGTM, Please only edit the commit message, adding "cnf-tests: " to the prefix so it will pass CI, plus please if you can, elaborate about the additional option - "PR_URLS" var, which is coming from the "Depends-On:" label in the commit message, or omit it if you didn't deliberatly put it there.

**Comment by sshnaidm** [comment]
```
{"level":"info","msg":"Logs for container test in pod ci:","time":"2024-02-28T08:32:27Z"}
{"level":"info","msg":"hack/verify-commits.sh\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  5786  100  5786    0     0  50179      0 --:--:-- --:--:-- --:--:-- 50313\ncommits between 35f4586fd0b532c898bf556a3f833e8c021f0ac6..HEAD:\n8c0416f0 Merge commit '723c30d507b737766c366e9eab03796b7d177a87'\n723c30d5 Checkout sriov repo to PULL_URL HEAD if PULL_URL is from sriov repo\n\nERROR: commit msg subject must include component name\nvalidation failed for 723c30d5\nmake: *** [Makefile:95: verify-commits] Error 20\n{\"component\":\"entrypoint\",\"error\":\"wrapped process failed: exit status 2\",\"file\":\"k8s.io/test-infra/prow/entrypoint/run.go:84\",\"func\":\"k8s.io/test-infra/prow/entrypoint.Options.internalRun\",\"level\":\"error\",\"msg\":\"Error executing test process\",\"severity\":\"error\",\"time\":\"2024-02-28T08:32:27Z\"}","time":"2024-02-28T08:32:27Z"}
```
Please add 'infra:' to the beginning of commit and PR name.

**Comment by sshnaidm** [comment]
@liornoy @SchSeba please review

**Comment by liornoy** [comment]
Please re-word the commit title to be less than 52 chars so it won't wrap and have the "...". Also a typo in the commit message: "operaotr".

**Review by sshnaidm — APPROVED** [review]
/lgtm

**Comment by liornoy** [comment]
lgtm. thanks!

**Review by SchSeba — COMMENTED** [review]
wait this will not help you achive what you want
the bundle is not interesting the part that we want is to build the components of the sriov operator 

please take a look how we do it in the repo itself
https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/hack/run-e2e-conformance-virtual-ocp.sh

**Comment by SchSeba** [comment]
Hi @sshnaidm @danimjaffe can we close this PR now that we have a running CI for sriov?

**Pull request closed without merging**
