### PR TITLE
Remove the creation of ~/bin and .bashrc as pods run /bin/sh

### PR DESCRIPTION
**Pull request by fedepaol**
Trying to fix CI failures.

### CODE REVIEW

**Comment by fedepaol** [comment]
I thikn

> Do they invoke like "/bin/sh -c" ... ?
> That explains why .bashrc is ignored.
> anyway it looks good to me, bar the fact I don't know what "GIMME_ENV" was used for

I think it was meant to display gimme setup.

**Comment by fromanirh** [comment]
> > Do they invoke like "/bin/sh -c" ... ?
> > That explains why .bashrc is ignored.
> > anyway it looks good to me, bar the fact I don't know what "GIMME_ENV" was used for
> 
> Edit: I misunderstood the question. GIMME_ENV was setting up PATH to /root/.gimme/ installed binaries and it was being ignored anyway. That's why we had to explicitly add `ENV PATH=$PATH:/root/.gimme/versions/go"$GOVERSION".linux.amd64/bin:$GOBIN` so my assumption is that it's safe to remove it. Ci is broken anyway so it's worth trying.

makes sense.

**Pull request merged**
