### PR TITLE
Find SCTP MachineConfigPool also via MatchLabels

### PR DESCRIPTION
**Pull request by oribon**
https://github.com/openshift-kni/cnf-features-deploy/issues/372

### CODE REVIEW

**Comment by yuvalk** [comment]
@fedepaol 
maybe it's a better idea altogether to start a job/pod and search for a node with the module?
this way is more generic and can fit outside OCP as well

**Comment by SchSeba** [comment]
/lgtm

holding until we branch this is for an SNO.
/hold

**Comment by fedepaol** [comment]
> @fedepaol
> maybe it's a better idea altogether to start a job/pod and search for a node with the module?
> this way is more generic and can fit outside OCP as well

Agree for outside OCP, but as a short term solution I'd leave as it is (and address all / as much dependencies from MCP all together). If we only change this bit, there will be still other places around that look for MCs.
Also, start a pod may not scale if the cluster has 10000 nodes and only one has the module loaded (while this gives you back a selector).

**Comment by yuvalk** [comment]
> > @fedepaol
> > maybe it's a better idea altogether to start a job/pod and search for a node with the module?
> > this way is more generic and can fit outside OCP as well
> 
> Agree for outside OCP, but as a short term solution I'd leave as it is (and address all / as much dependencies from MCP all together). If we only change this bit, there will be still other places around that look for MCs.
> Also, start a pod may not scale if the cluster has 10000 nodes and only one has the module loaded (while this gives you back a selector).

the other, longer term, option is to enhance ptp-operator to report ptp functionality as a node resource

**Comment by fedepaol** [comment]
Just thinking, do we need this also for the ux_32 module? I think it suffers from the same issue

**Pull request merged**
