### PR TITLE
Update PAO tests

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Latest changes under the PAO includes removing of the feature gate code.

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by fedepaol** [comment]
@art is this 4.6 only, right?

**Comment by cynepco3hahue** [comment]
> @cynepco3hahue is this 4.6 only, right?

Yes.

**Comment by cynepco3hahue** [comment]
Not relevant anymore.

**Pull request closed without merging**
