### PR TITLE
Check for having at least one node so tests won't panic.

### PR DESCRIPTION
**Pull request by fedepaol**
Let's check if we have at least one available node and if not let's fail gracefully.

### CODE REVIEW

**Comment by davidvossel** [comment]
e2e failed before even executing our logic. so it's not us. 

```level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"```

**Comment by fedepaol** [comment]
CI passed! All the workarounds in place are working now.

**Pull request merged**
