### PR TITLE
Add a holdInstallation flag to SiteConfig

### PR DESCRIPTION
**Pull request by leo8a**
Since for Telco ZTP we're targeting e2e deployments with no user action, I just set the default value to false.

Signed-off-by: Leo Ochoa [lochoa@redhat.com](mailto:lochoa@redhat.com)

### CODE REVIEW

**Comment by leo8a** [comment]
pushed again with some fixes to other nits on the spec

**Comment by imiller0** [comment]
/hold
Adding a hold until the 4.12 release branch is created.

**Review by imiller0 — COMMENTED** [review]
@leo8a Thanks for adding this functionality! Is there a particular use case where this is needed?

Can you add to the PR CI validation tests (here is [one example](https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go#L214))

**Comment by leo8a** [comment]
> Thanks for adding this functionality! Is there a particular use case where this is needed?

Thanks for taking a look. Although Telco ZTP expects this holdInstallation as false (hence the default assignment), there might be some times that the admin/user might want to pause the cluster installation for troubleshooting any issue with the deployment before continuing till the end.

If holdInstallation is set to true, the day1 installation flow is paused and can be resumed at any moment. More info on [PR#2293](https://github.com/openshift/assisted-service/pull/2293).

**Review by serngawy — APPROVED** [review]

**Pull request merged**
