### PR TITLE
Disable ptp test as measuring the latency with master + slave on nodes is not meaningful.

### PR DESCRIPTION
**Pull request by fedepaol**

### CODE REVIEW

**Comment by yuvalk** [comment]
can you try and say something more meaningful in the commit msg? (pun intended) 

````
Disable PTP Latency Tests

Can't test for >100us without external HW
```
or something

**Comment by fedepaol** [comment]
/override ci/prow/e2e-gcp 
Last fail is a flake, changed only the commit message.
Those tests are not impacted by the change either.

**Pull request merged**
