### PR TITLE
cnf-tests: Bump operators to `4.15`

### PR DESCRIPTION
**Pull request by zeeke**
Bump all references from 4.14 to 4.15 in the project. Nighlty CI deployment is based on
`common.sh#OPERATOR_VERSION` env variable.

https://github.com/openshift-kni/cnf-features-deploy/blob/master/hack/common.sh#L19C8-L19C24

Nightly CI is currently running against 4.14 ([periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests/1713744857857527808](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests/1713744857857527808)):

```
          git clone --single-branch --branch release-4.14 https://github.com/openshift/sriov-network-operator.git
          cd sriov-network-operator
          podman build -f bundleci.Dockerfile --tag image-registry.openshift-image-registry.svc:5000/openshift-marketplace/sriov-operator-bundle:latest .
          podman push image-registry.openshift-image-registry.svc:5000/openshift-marketplace/sriov-operator-bundle:latest --tls-verify=false
          cd ..
```

### CODE REVIEW

**Comment by liornoy** [comment]
@zeeke the e2e-gcp-ovn failure here, is a known issue with NTO that is not related to this PR.
I think we can override.

**Comment by zeeke** [comment]
/override ci/prow/e2e-gcp-ovn

@liornoy thanks for checking that!

Failing test is
```
[It] [rfe_id:27363][performance] CPU Management when pod runs with the CPU load balancing runtime class [test_id:32646] should disable CPU load balancing for CPU's used by the pod 
```

**Pull request merged**
