### PR TITLE
Bug 1894861: Switch to the PAO namespace used in the docs and make the namespaces configurable

### PR DESCRIPTION
**Pull request by fedepaol**
When installing an operator, the user can choose the namespace where to install
it. The common behaviour is to use the one described in the docs, which is different
for the one being used here.

On top of that, we are making the namespaces related to the other two operators
(ptp, sriov) configurable for what is related to the tests implemented here.

Finally, the deploy part is updated to create and use the new default namespace
for PAO.

### CODE REVIEW

**Comment by fedepaol** [comment]
/retitle Bug 1894861: Switch to the PAO namespace used in the docs and make the namespaces configurable

**Comment by fedepaol** [comment]
Expected failures, will converge when https://github.com/openshift-kni/performance-addon-operators/pull/437 will be merged

**Review by SchSeba — APPROVED** [review]
/lgtm

**Pull request merged**
