### PR TITLE
Add the n3000 and sriov-fec operators develop by intel

### PR DESCRIPTION
**Pull request by SchSeba**
This commit add the two operators develop by intel.
I also add this to the DU profile

Signed-off-by: Sebastian Sch <sebassch@gmail.com>

### CODE REVIEW

**Review by vitus133 — APPROVED** [review]

**Comment by SchSeba** [comment]
CI error:

```
[WARN] Deployment of feature 'ran-profile-gcp' failed.
[WARN] Deployment did not fully succeed yet, retrying in 10 sec, 71 retries left
[INFO] Deploying feature 'ran-profile-gcp' for environment 'cn-ran-overlays'
Error: accumulating resources: 2 errors occurred:
	* accumulateFile error: "accumulating resources from '../ran-profile': '/go/src/github.com/openshift-kni/cnf-features-deploy/feature-configs/cn-ran-overlays/ran-profile' must resolve to a file"
	* accumulateDirector error: "recursed accumulation of path '/go/src/github.com/openshift-kni/cnf-features-deploy/feature-configs/cn-ran-overlays/ran-profile': accumulating resources: 2 errors occurred:\n\t* accumulateFile error: \"accumulating resources from 'cluster-config': '/go/src/github.com/openshift-kni/cnf-features-deploy/feature-configs/cn-ran-overlays/ran-profile/cluster-config' must resolve to a file\"\n\t* accumulateDirector error: \"recursed accumulation of path '/go/src/github.com/openshift-kni/cnf-features-deploy/feature-configs/cn-ran-overlays/ran-profile/cluster-config': accumulating resources: 2 errors occurred:\\n\\t* accumulateFile error: \\\"accumulating resources from '../../../deploy/sriov-fec': '/go/src/github.com/openshift-kni/cnf-features-deploy/feature-configs/deploy/sriov-fec' must resolve to a file\\\"\\n\\t* accumulateDirector error: \\\"recursed merging from path '/go/src/github.com/openshift-kni/cnf-features-deploy/feature-configs/deploy/sriov-fec': may not add resource with an already registered id: ~G_v1_Namespace|~X|n3000-operators-resources\\\"\\n\\n\"\n\n"
```

This is because the n3000 and the sriov-fec both request to create the same namespace and that is not supported.
https://github.com/kubernetes-sigs/kustomize/issues/2747

For now I will remove the namespace creation from the sriov-fec as today they should be install together but in the future that is not the case I will work with intel to separate them to different namespaces

**Comment by fedepaol** [comment]
/lgtm

Do we want to deploy it also on the regular lane?

**Comment by SchSeba** [comment]
@fedepaol I prefer to leave this as part of the ran profile as this is going to be deploy only for runs

**Pull request merged**
