### PR TITLE
Bug 2038954: ztp: ClusterVersion changes for platform upgrade

### PR DESCRIPTION
**Pull request by nishant-parekh**
ztp: sync clusterVersion changes from master
  
   added status.history section to verify updates

Signed-off-by: Nishant Parekh <nparekh@redhat.com>

### CODE REVIEW

**Comment by yliu127** [comment]
LGTM

**Comment by Missxiaoguo** [comment]
We should close this one and merge PR995 to master, then cherry pick it to 4.10

**Review by serngawy — APPROVED** [review]

**Pull request merged**
