### PR TITLE
infra: CNF-14990: Replace abandoned gimme tool & Provide alignment for golang version

### PR DESCRIPTION
**Pull request by fontivan**
- Since golang 1.21, go is much better at managing its own version requirements (https://go.dev/doc/toolchain)
- The gimme tool seems to be abandoned and does not work correctly for modern go versions (https://github.com/travis-ci/gimme/issues/210)
- Designate the top level go.mod as the source of truth for the go version in the project
- Includes notes on where this version needs to be updated to match
- Update fedora image used in ci job to fedora 40 since it provides golang 1.22 in its repos

### CODE REVIEW

**Comment by fontivan** [comment]
The three failing CI tests ares failing since the CI does not use build root from the pr but instead from HEAD of the target branch. More details are available in https://issues.redhat.com/browse/CNF-15003

**Review by lack — APPROVED** [review]

**Comment by lack** [comment]
/override ci/prow/e2e-aws-ran-profile ci/prow/images ci/prow/e2e-aws-ci-tests

**Pull request merged**
