### PR TITLE
Pin the performance-addon-operator version to release-4.10

### PR DESCRIPTION
**Pull request by cynepco3hahue**
The PR includes some important changes:
- Advance the go version to 1.17, which can be reviewed as a separate PR under https://github.com/openshift-kni/cnf-features-deploy/pull/932.
- Copy the Intel FPGA API to the repo instead of vendoring it to avoid conflicts with the old version of logr package.
- Advance k8s dependencies to 1.23.
- Pin PAO dependencies to release-4.10.

### CODE REVIEW

**Comment by lack** [comment]
Looking at these test failures, the sctp failures look "normal" :( but the gatekeeper test panic looks new...

**Comment by cynepco3hahue** [comment]
> Looking at these test failures, the sctp failures look "normal" :( but the gatekeeper test panic looks new...

Yee, will investigate it today. Also, I can see some PAO tests failed because of the insufficient CPU
```
Feb  9 23:27:31.649: [WARNING]: -> Scheduling FailedScheduling 0/6 nodes are available: 1 Insufficient cpu, 2 node(s) didn't match Pod's node affinity/selector, 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
Feb  9 23:27:31.649: [WARNING]: -> Scheduling FailedScheduling 0/6 nodes are available: 1 Insufficient cpu, 2 node(s) didn't match Pod's node affinity/selector, 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
[AfterEach] Verification of cpu manager functionality
```

**Comment by cynepco3hahue** [comment]
@lack I think it is some flaky tests because every time I can see a different number of SCTP failures

**Pull request merged**
