### PR TITLE
vendor: align 4.11 branch to NTO 4.11 20220904

### PR DESCRIPTION
**Pull request by yanirq**

### CODE REVIEW

**Comment by SchSeba** [comment]
Hi @yanirq do we need all the other commits in the list?

should it be only the vendor bump?

**Comment by yanirq** [comment]
> Hi @yanirq do we need all the other commits in the list?
> 
> should it be only the vendor bump?

I will probably have to rebase that (maybe even open a new PR instead)

**Comment by fromanirh** [comment]
I'd like to bump once https://github.com/openshift/cluster-node-tuning-operator/pull/404 is in

**Comment by SchSeba** [comment]
/hold

waiting for a merge and backport  on https://github.com/openshift/cluster-node-tuning-operator/pull/404

**Comment by fromanirh** [comment]
/hold
...but this PR needs to be updated

**Comment by yanirq** [comment]
> /unhold [openshift/cluster-node-tuning-operator#404](https://github.com/openshift/cluster-node-tuning-operator/pull/404) merged

We will need the 4.11 cherry pick since this is an alignment for 4.11

**Comment by yanirq** [comment]
@SchSeba   I can see an `validation sro`  failing here the ran profile tests, are you familiar with that issue ?

**Comment by SchSeba** [comment]
Hi @yanirq can we close this one?

**Pull request closed without merging**
