### PR TITLE
OCPBUGS-39149: ztp: ignore empty file in siteconfig extra manifests

### PR DESCRIPTION
**Pull request by abraham2512**
This includes a fix for the ZTP siteconfig-generator panic if an empty file exists in the extra-manifest directory.
The condition checks and ignores empty files silently.
Also includes a unit test for testing the scenario with empty file.

/cc @sabbir-47

### CODE REVIEW

**Comment by abraham2512** [comment]
@sabbir-47 could you please add lgtm label, thanks

**Comment by sabbir-47** [comment]
Looks good to me, wanted to have another eye.

**Pull request merged**
