### PR TITLE
Update performance profile to reflect api changes

### PR DESCRIPTION
**Pull request by davidvossel**
Updates our base performance profile to reflect the api changes in this pr, https://github.com/openshift-kni/performance-addon-operators/pull/73

### CODE REVIEW

**Comment by davidvossel** [comment]
/hold

waiting until https://github.com/openshift-kni/performance-addon-operators/pull/73 is merged

**Comment by davidvossel** [comment]
I updated this to reflect the boolean name change. spec.cpu.balanceIsolated defaults to true now once this PR gets merged, https://github.com/openshift-kni/performance-addon-operators/pull/73

**Comment by slintes** [comment]
ci/prow/e2e-gcp is green

/lgtm

**Pull request merged**
