### PR TITLE
Fix typos in README.md

### PR DESCRIPTION
**Pull request by ryandgoulding**
Just fixes a few typos in README.md.

Signed-off-by: Ryan Goulding <rgouldin@redhat.com>

### CODE REVIEW

**Comment by fedepaol** [comment]
Thanks @ryandgoulding !

**Comment by fedepaol** [comment]
/override ci/prow/e2e-gcp

Doc only, no harm

**Comment by yuvalk** [comment]
yeah, this is ridiculous 
/override ci/prow/e2e-gcp-ran-profile

**Comment by yuvalk** [comment]
/override ci/prow/e2e-gcp-origin
/override ci/prow/e2e-gcp-ovn 

as we wrote - this is a doc only PR

**Comment by SchSeba** [comment]
closing this one
/close

**Pull request closed without merging**
