### PR TITLE
cnf-tests: Use the built-in oc kustomize

### PR DESCRIPTION
**Pull request by liornoy**
Use the built-in `oc kustomize` instead of downloading from github.
This change is required to resolve the following error:

Downloading the Kustomize tool
/tmp/shared/cnf/cnf-features-deploy /shared/cnf/cnf-features-deploy
Github rate-limiter failed the request.
Either authenticate or wait a couple of minutes.

### CODE REVIEW

**Comment by liornoy** [comment]
Testing CI on: https://github.com/openshift/release/pull/39149

**Comment by sshnaidm** [comment]
Tested in jobs:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/39149/rehearse-39149-periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-cnftests/1655943427050704896
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/39149/rehearse-39149-periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-cnftests/1655943458700922880

/lgtm

**Comment by yuvalk** [comment]
@vitus133 can you please review? do you ppl still need this functionality?

anyhow, checked now,
even if the kustomize functionality is needed, it's already in kubectl since may 2021.. (and in k8s since 1.22 which is part of OCP 4.9)
so I think we're even safe from that respect

**Review by vitus133 — APPROVED** [review]
Awesome

**Pull request merged**
