### PR TITLE
OCPBUGS-34603:  Add a new set of PTP configurations for events in source CRs with additional PTP options

### PR DESCRIPTION
**Pull request by aneeshkp**
Current source crs PTP doesn't have any reference config for events .
This PR  copies non event PTPConfig  as new file with 'ForEvent' prefix and adds events required ptp  options to the config .
ztp/source-crs/PtpConfigBoundaryForEvent.yaml
ztp/source-crs/PtpConfigForHAForEvent.yaml
ztp/source-crs/PtpConfigMasterForEvent.yaml
ztp/source-crs/PtpConfigSlaveForEvent.yaml

### CODE REVIEW

**Comment by jzding** [comment]
These 2 configs have events enabled. Could you change the file name to *ForEvent.yaml and create non-event versions of them?
PtpConfigGmWpc.yaml
PtpConfigDualCardGmWpc.yaml

**Comment by jzding** [comment]
This line have the -r option duplicated `-r -r` . Could you fix it here as well?
https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/source-crs/PtpConfigMaster.yaml#L16

**Review by jzding — APPROVED** [review]
/lgtm

**Comment by sabbir-47** [comment]
@aneeshkp @jzding Are this mandatory config? Meaning, should this be applied as a default config at day-2?

**Comment by aneeshkp** [comment]
@sabbir-47 yes! if they are  enabling events by default . right now there is a gap between reference config for events in this repor and openshift docs

**Review by nishant-parekh — APPROVED** [review]

**Pull request merged**
