### PR TITLE
Add README for resource-generator

### PR DESCRIPTION
**Pull request by imiller0**
Add README for resource-generator and minor corrections to other README
files.

Signed-off-by: Ian Miller <imiller@redhat.com>

### CODE REVIEW

**Comment by vitus133** [comment]
Hi,
Just a couple of small things. 
1. ztp/resource-generator/assets folder is safe to remove, since ztp/resource-generator/README.md is not using the picture it contains.
2. The commit message must start from "ztp:"
Other than that - fantastic!

**Comment by imiller0** [comment]
I've added a reference to the diagram in assets/flow.png. Thanks for the pointer!

**Pull request merged**
