### PR TITLE
[release-4.4] Use new 4.4 performance operator snapshot image

### PR DESCRIPTION
**Pull request by slintes**

### CODE REVIEW

**Comment by slintes** [comment]
@fedepaol what is good time to do this for release-4.5 (`4.5-snapshot`) and master (`4.6-snapshot`)?
I don't want to cause merge conflicts :)

**Comment by fedepaol** [comment]
> @fedepaol what is good time to do this for release-4.5 (`4.5-snapshot`) and master (`4.6-snapshot`)?
> I don't want to cause merge conflicts slightly_smiling_face
> 

Thanks, I really appreciate that. I would wait until the new layout lands.

**Comment by slintes** [comment]
/retest

also created PRs for 4.5 and master

**Pull request merged**
