### PR TITLE
OCPBUGS-16094: Revert "OCPBUGS-3513: use manifestsConfigMapRefs "

### PR DESCRIPTION
**Pull request by pixelsoccupied**
Reverts openshift-kni/cnf-features-deploy#1526

see: https://issues.redhat.com/browse/OCPBUGS-16094 

/cc @lack 
/cc @imiller0

### CODE REVIEW

**Comment by pixelsoccupied** [comment]
CI failing cause of aws...will rerun later today. But IMO this revert will not affect any e2es tests

**Review by imiller0 — APPROVED** [review]
/lgtm

**Pull request merged**
